config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'home#index'
  get 'privacy', to: 'home#privacy'
  get 'terms', to: 'home#terms'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create] do
    collection do
      get :comments
    end
  end
  resources :shoes do
    resources :comments, only: %i[create update destroy], shallow: true
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :mypage, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: [:new, :create]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :shoes
    resources :users, only: %i[index edit update show destroy]
  end
end

app/views/shared/_before_login_header.html.erb
<header class="header">
  <div class="header__inner">
    <div class="header__logo">
      <%= link_to root_path do %>
        <%= image_tag "shoes.svg", class: "header__img", :alt => 'ロゴ画像' %>
        <h1 class="header__title">shoes for runners</h1>
      <% end %>
    </div>
    <div class="header__gnav-btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div class="header__bglayer"></div>
    <nav class="header__nav">
      <ul class="header__list">
        <li><%= link_to (t 'shoes.index.title'), shoes_path, class: "header__item" %></li>
        <li><%= link_to (t 'defaults.guest_login'), guest_login_path, method: :post, class: "header__item" %></li>
        <li><%= link_to (t 'defaults.login'), login_path, class: "header__item" %></li>
      </ul>
    </nav>
  </div>
</header>

<%= javascript_pack_tag "pages/header", defer: true %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
        <div class="footer__inner">
            <div class="footer__title-link">
              <%= link_to 'Shoes for runners', root_path, class: "footer-logo text-decoration-none" %>
            </div>
            <div class="footer__link">
                <div class="footer__privacy">
                  <%= link_to t('home.privacy.link-name'), privacy_path, class: "footer-text text-decoration-none" %>
                </div>
                <div class="footer__privacy">
                  <%= link_to t('home.terms.title'), terms_path, class: "footer-text text-decoration-none" %>
                </div>
                <div class="footer__inquiry">
                  <%= link_to t('contacts.new.title'), new_contact_path, class: "footer-text text-decoration-none" %>
                </div>

            </div>
            <div class="footer__cr">
                <small>&copy;Shoes for runners , All Rights Reserved.</small>
            </div>
        </div>
    </footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header__inner">
    <div class="header__logo">
      <%= link_to root_path do %>
        <%= image_tag "shoes.svg", class: "header__img", :alt => 'ロゴ画像' %>
        <h1 class="header__title">shoes for runners</h1>
      <% end %>
    </div>
    <div class="header__gnav-btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div class="header__bglayer"></div>
    <nav class="header__nav">
      <ul class="header__list">
        <li><%= link_to t('shoes.index.title'), shoes_path, class: "header__item" %></li>
        <li><%= link_to t('mypages.show.title'), mypage_path, class: "header__item" %></li>
        <li><%= link_to t('shoes.bookmarks.title'), bookmarks_shoes_path, class: "header__item" %></li>
        <li><%= link_to t('users.comments.title'), comments_users_path, class: "header__item" %></li>
        <li><%= link_to t('defaults.logout'), logout_path, method: :delete, class: "header__item" %></li>
      </ul>
    </nav>
  </div>
</header>

<%= javascript_pack_tag "pages/header", defer: true %>