config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'home#index'
  get 'privacy', to: 'home#privacy'
  get 'terms', to: 'home#terms'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create] do
    collection do
      get :comments
    end
  end
  resources :shoes do
    resources :comments, only: %i[create update destroy], shallow: true
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :mypage, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: [:new, :create]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :shoes
    resources :users, only: %i[index edit update show destroy]
  end
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :name, uniqueness: { case_sensitive: true }, presence: true
  validates :url, presence: true
  validates :img_url, presence: true

  enum gender: { man: 0, woman: 1 }
  enum purpose: { jogging: 0, racing: 1 }
  enum maker: { nike: 0, adidas: 1, mizuno: 2, asics: 3 }
  enum level: {beginner: 0, intermediate: 1, advanced: 2 }
end

app/controllers/admin/shoes_controller.rb
class Admin::ShoesController < Admin::BaseController
  before_action :set_shoe, only: %i[show edit update destroy]

  def new
    @shoe = Shoe.new
  end

  def create
    @shoe = current_user.shoes.build(shoe_params)

    if @shoe.save
      redirect_to new_admin_shoe_path, success: t('defaults.message.added', item: Shoe.model_name.human)
    else

      flash.now[:danger] = t('defaults.message.not_added', item: Shoe.model_name.human)
      render :new
    end
  end

  def index
    @q = Shoe.ransack(params[:q])
    @shoes = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def update
    if @shoe.update(shoe_params)
      redirect_to admin_shoe_path(@shoe), success: t('defaults.message.updated', item: Shoe.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Shoe.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @shoe.destroy!
    redirect_to admin_shoes_path, success: t('defaults.message.deleted', item: Shoe.model_name.human)
  end

  private

  def shoe_params
    params.require(:shoe).permit(:name, :url, :img_url, :gender, :purpose, :maker, :level)
  end

  def set_shoe
    @shoe = Shoe.find(params[:id])
  end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def index
    @q = Shoe.ransack(params[:q])
    @shoes = @q.result(distinct: true).all
  end

  def show
    @shoe = Shoe.find(params[:id])
    @comment = Comment.new
    @comments = @shoe.comments.includes(:user).order(created_at: :desc)
  end

  def bookmarks
    @bookmark_shoes = current_user.bookmark_shoes.includes(:user).order(created_at: :asc)
  end
end

app/views/shoes/_bookmark.html.erb
<%= link_to bookmarks_path(shoe_id: shoe.id),
          id: "js-bookmark-button-for-shoe-#{shoe.id}",
          method: :post,
          remote: true do %>
  <%= image_tag "unbookmark-icon.svg", :alt => 'ブックマークしていないことを表すアイコン' %>
<% end %>

app/views/shoes/_bookmark_button.html.erb
<% if current_user.bookmark?(shoe) %>
  <%= render 'unbookmark', { shoe: shoe } %>
<% else %>
  <%= render 'bookmark', { shoe: shoe } %>
<% end %>

app/views/shoes/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to '#', id: "button-edit-#{shoe.id}" do %>
      <%= image_tag "pencil.svg", :alt => '鉛筆' %>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to '#', id: "button-delete-#{shoe.id}" do %>
      <%= image_tag "trash-can.svg", :alt => 'ゴミ箱' %>
    <% end %>
  </li>
</ul>

app/views/shoes/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class="shoes-search">
    <div class="shoes-search__inner">
      <div class="shoes-search__group">
          <%= f.label :gender_cont, 'メンズ or レディース シューズ選択', class:'shoes-search__title' %>
          <%= f.select :gender_cont, Shoe.genders_i18n.invert.map{|key, value| [key, Shoe.genders[value]]}, { include_blank: '選択してください'}, { class: 'shoes-search__select' , required: true } %>
      </div>
      <div class="shoes-search__group">
          <%= f.label :purpose_cont,  'ジョギング用 or レース用シューズ選択', class:'shoes-search__title' %>
          <%= f.select :purpose_cont, Shoe.purposes_i18n.invert.map{|key, value| [key, Shoe.purposes[value]]}, { include_blank: '選択してください'}, { class: 'shoes-search__select' , required: true } %>
      </div>
      </div>
      <div class="shoes-search__group">
          <%= f.label :maker_cont,  'メーカー選択', class:'shoes-search__title' %>
          <%= f.select :maker_cont, Shoe.makers_i18n.invert.map{|key, value| [key, Shoe.makers[value]]}, { include_blank: '選択してください'}, { class: 'shoes-search__select' , required: true } %>
      </div>
      <div class="shoes-search__group">
          <%= f.label :level_cont,  '走力レベル選択', class:'shoes-search__title' %>
          <%= f.select :level_cont, Shoe.levels_i18n.invert.map{|key, value| [key, Shoe.levels[value]]}, { include_blank: '選択してください'}, { class: 'shoes-search__select' , required: true } %>
      </div>
    </div>
    <%= f.submit (t 'defaults.search'), class: 'shoes-search__btn'%>
  </div>
<% end %>

app/views/shoes/_shoe.html.erb
<div class="shoe">
  <div id="shoe-id-<%= shoe.id %>">
    <div class="shoe__card">
      <a href=<%= shoe.url %> target="_blank" rel="nofollow sponsored noopener" style="word-wrap:break-word;"  ><img src=<%= shoe.img_url %> border="0" style="margin:2px" alt="" title=""></a>
        <div class="shoe__card-causion">
          ※上記画像をクリックすると<br>楽天商品ページへと移動します
        </div>
      <div class="shoe__card-title">
        <%= shoe.name %>
      </div>
      <div class="shoe__card-btn">
        <%= link_to '詳細画面へ', shoe_path(shoe), class: "shoe__card-link" %>
      </div>
    </div>
  </div>
</div>

app/views/shoes/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(shoe_id: shoe.id)),
          id: "js-bookmark-button-for-shoe-#{shoe.id}",
          method: :delete,
          remote: true do %>
  <%= image_tag "bookmark-icon.svg", :alt => 'ブックマークしていることを表すアイコン' %>
<% end %>

app/views/shoes/bookmarks.html.erb
<!-- ブックマークしたシューズ一覧 -->
<% content_for(:title, t('.title')) %>
<div class="shoes-list">
  <div class="shoes-list__inner">
    <div>
      <h2 class="shoes-list__title"><%= t '.title' %></h2>
    </div>
    <div class="shoes-list__item">
      <% if @bookmark_shoes.present? %>
        <%= render @bookmark_shoes %>
      <% else %>
        <p class="shoes-list__result"><%= t('.no_result') %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/shoes/index.html.erb
<!-- シューズ一覧 -->
<% content_for(:title, t('.title')) %>
<div class="shoes-list">
  <div class="shoes-list__inner">
    <h2 class="shoes-list__title"><%= t '.title' %></h2>
    <p class="shoes-list__explanation">下の4つの項目にご回答していただくと、おすすめシューズが表示されます。</p>
    <div>
      <%= render 'search_form', url: shoes_path %>
    </div>
    <div class="shoes-list__items-inner">
      <div class="shoes-list__item">
        <% if @shoes.present? %>
          <%= render @shoes %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shoes/show.html.erb
<% content_for(:title, @shoe.name) %>
<div class="shoes-detail">
  <div id="shoe-id-<%= @shoe.id %>">
    <div class="shoes-detail__inner">
      <h1 class="shoes-detail__title"><%= t '.title' %></h1>
      <!-- 掲示板内容 -->
      <% if logged_in? %>
        <div class="shoes-detail__bookmark-btn">
          <%= render 'bookmark_button', shoe: @shoe %>
        </div>
      <% end %>
      <div class="shoes-detail__img">
        <a href=<%= @shoe.url %> target="_blank" rel="nofollow sponsored noopener" style="word-wrap:break-word;"  ><img src=<%= @shoe.img_url %> border="0" style="margin:2px" alt="" title=""></a>
      </div>
      <div class="shoes-detail__causion">
        ※上記画像をクリックすると<br>楽天商品ページへと移動します
      </div>
      <div class="shoes-detail__text">
        <h2 class="shoes-detail__explanation">シューズ名：<%= @shoe.name %></h2>
        <h2 class="shoes-detail__explanation">メンズ or レディース：<%= @shoe.gender_i18n %></h2>
        <h2 class="shoes-detail__explanation">メーカー：<%= @shoe.maker_i18n %></h2>
        <h2 class="shoes-detail__explanation">使用目的：<%= @shoe.purpose_i18n %></h2>
        <h2 class="shoes-detail__explanation">レベル：<%= @shoe.level_i18n %></h2>
      </div>
    </div>
  </div>

  <!-- コメントフォーム -->
  <%= render 'comments/form', { shoe: @shoe, comment: @comment } %>

  <!-- コメントエリア -->
  <%= render 'comments/comments', { comments: @comments } %>
</div>