config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'home#index'
  get 'privacy', to: 'home#privacy'
  get 'terms', to: 'home#terms'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create] do
    collection do
      get :comments
    end
  end
  resources :shoes do
    resources :comments, only: %i[create update destroy], shallow: true
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :mypage, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :contacts, only: [:new, :create]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :shoes
    resources :users, only: %i[index edit update show destroy]
  end
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :name, uniqueness: { case_sensitive: true }, presence: true
  validates :url, presence: true
  validates :img_url, presence: true

  enum gender: { man: 0, woman: 1 }
  enum purpose: { jogging: 0, racing: 1 }
  enum maker: { nike: 0, adidas: 1, mizuno: 2, asics: 3 }
  enum level: {beginner: 0, intermediate: 1, advanced: 2 }
end

app/controllers/admin/shoes_controller.rb
class Admin::ShoesController < Admin::BaseController
  before_action :set_shoe, only: %i[show edit update destroy]

  def new
    @shoe = Shoe.new
  end

  def create
    @shoe = current_user.shoes.build(shoe_params)

    if @shoe.save
      redirect_to new_admin_shoe_path, success: t('defaults.message.added', item: Shoe.model_name.human)
    else

      flash.now[:danger] = t('defaults.message.not_added', item: Shoe.model_name.human)
      render :new
    end
  end

  def index
    @q = Shoe.ransack(params[:q])
    @shoes = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def update
    if @shoe.update(shoe_params)
      redirect_to admin_shoe_path(@shoe), success: t('defaults.message.updated', item: Shoe.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Shoe.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @shoe.destroy!
    redirect_to admin_shoes_path, success: t('defaults.message.deleted', item: Shoe.model_name.human)
  end

  private

  def shoe_params
    params.require(:shoe).permit(:name, :url, :img_url, :gender, :purpose, :maker, :level)
  end

  def set_shoe
    @shoe = Shoe.find(params[:id])
  end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def index
    @q = Shoe.ransack(params[:q])
    @shoes = @q.result(distinct: true).all
  end

  def show
    @shoe = Shoe.find(params[:id])
    @comment = Comment.new
    @comments = @shoe.comments.includes(:user).order(created_at: :desc)
  end

  def bookmarks
    @bookmark_shoes = current_user.bookmark_shoes.includes(:user).order(created_at: :asc)
  end
end

app/views/admin/shoes/_search_form.html.erb
<%= search_form_for @q, url: admin_shoes_path do |f| %>
  <div class="row">
    <div class="form-inline align-items-center mx-auto">
      <div class="col-auto">
        <%= f.search_field :name_cont, class: 'form-control', placeholder: t('defaults.search_shoes') %>
      </div>
      <div class="col-auto">
        <%= f.date_field :created_at_gteq, class: 'form-control' %>
        <span>〜</span>
        <%= f.date_field :created_at_lteq_end_of_day, class: 'form-control' %>
      </div>
      <div class="col-auto">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/shoes/_shoe.html.erb
<tr>
  <td>
    <%= shoe.id %>
  </td>
  <td>
    <%= shoe.name %>
  </td>
  <td>
    <%= shoe.gender_i18n %>
  </td>
  <td>
    <%= shoe.purpose_i18n %>
  </td>
  <td>
    <%= shoe.maker_i18n %>
  </td>
  <td>
    <%= shoe.level_i18n %>
  </td>
  <td>
    <%= l shoe.created_at, format: :long %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admin_shoe_path(shoe), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admin_shoe_path(shoe), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admin_shoe_path(shoe), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/shoes/edit.html.erb
<% content_for(:title, @shoe.name) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 mt-3 mb-3">
      <h1><%= t '.title' %></h1>
      <%= form_with model: @shoe, url: admin_shoe_path(@shoe), local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :url %>
          <%= f.text_field :url, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :img_url %>
          <%= f.text_field :img_url, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :gender, 'メンズ or レディース シューズ選択'%>
          <%= f.select :gender, Shoe.genders_i18n.invert, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form-group">
          <%= f.label :purpose,  'ジョギング用 or レース用シューズ選択', class:'float-left' %>
          <%= f.select :purpose, Shoe.purposes_i18n.invert, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form-group">
          <%= f.label :maker,  'メーカー選択', class:'float-left' %>
          <%= f.select :maker, Shoe.makers_i18n.invert, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form-group">
          <%= f.label :level,  '走力レベル選択', class:'float-left' %>
          <%= f.select :level, Shoe.levels_i18n.invert, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="actions">
          <%= f.submit '送信', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/shoes/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-14 mb-3">
      <%= render 'search_form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= Shoe.human_attribute_name(:id) %></th>
          <th scope="col"><%= Shoe.human_attribute_name(:name) %></th>
          <th scope="col"><%= Shoe.human_attribute_name(:gender_admin) %></th>
          <th scope="col"><%= Shoe.human_attribute_name(:purpose) %></th>
          <th scope="col"><%= Shoe.human_attribute_name(:maker) %></th>
          <th scope="col"><%= Shoe.human_attribute_name(:level) %></th>
          <th scope="col"><%= Shoe.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <%= render @shoes %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <!-- ページネーション -->
      <%= paginate @shoes %>
    </div>
  </div>
</div>

app/views/admin/shoes/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 mt-3 mb-3">
      <h1><%= t '.title' %></h1>
      <%= form_with model: @shoe, url: admin_shoes_path, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :name, class:"float-left" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :url, class:"float-left" %>
          <%= f.text_field :url, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :img_url, class:"float-left" %><br>
          <%= f.text_field :img_url, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :gender, 'メンズ or レディース シューズ選択'%> <br>
          <%= f.select :gender, Shoe.genders_i18n.invert, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form-group">
          <%= f.label :purpose,  'ジョギング用 or レース用シューズ選択', class:'float-left' %> <br>
          <%= f.select :purpose, Shoe.purposes_i18n.invert, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form-group">
          <%= f.label :maker,  'メーカー選択', class:'float-left' %>
          <%= f.select :maker, Shoe.makers_i18n.invert, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form-group">
          <%= f.label :level,  '走力レベル選択', class:'float-left' %> <br>
          <%= f.select :level, Shoe.levels_i18n.invert, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="actions">
          <%= f.submit '送信', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/shoes/show.html.erb
<% content_for(:title, @shoe.name) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 mt-3 mb-3">
      <h1><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admin_shoe_path(@shoe), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admin_shoe_path(@shoe), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= Shoe.human_attribute_name(:id) %></th>
          <td><%= @shoe.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= Shoe.human_attribute_name(:name) %></th>
          <td><%= @shoe.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= Shoe.human_attribute_name(:gender) %></th>
          <td><%= @shoe.gender_i18n %></td>
        </tr>
        <tr>
          <th scope="row"><%= Shoe.human_attribute_name(:purpose) %></th>
          <td><%= @shoe.purpose_i18n %></td>
        </tr>
        <tr>
          <th scope="row"><%= Shoe.human_attribute_name(:maker) %></th>
          <td><%= @shoe.maker_i18n %></td>
        </tr>
        <tr>
          <th scope="row"><%= Shoe.human_attribute_name(:level) %></th>
          <td><%= @shoe.level_i18n %></td>
        </tr>
        <tr>
          <th scope="row"><%= Shoe.human_attribute_name(:created_at) %></th>
          <td><%= l @shoe.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>